#Load settings
threads=25
rampup=30
duration=300
loop=-1
throughput=25.0

#Application info
protocol=https
host=jsonplaceholder.typicode.com
port=443

#LoadDistribution
addpost_pctl=10.0
getposts_pctl=100.0
getpostbyid_pctl=50.0
getcomments_pctl=20.0
updatepost_pctl=10.0
patchpost_pctl=10.0
deletepost_pctl=5.0
